install.packages("devtools")
library(devtools)
install_github('slidify','ramnathv')
install_github('slidifyLibraries', 'ramnathv')
library(slidify)
getwd()
setwd("~/sample/project/")
author("Project on Slidify")
publish(user = "s31bis", repo = "DataSCience")
publish(title = 'mytitle', 'index.html', host = 'rpubs')